targets:
  dev:
    permissions:
      - group_name: admins
        level: CAN_MANAGE
    
    presets:
      name_prefix: (dev ${workspace.current_user.short_name})
      source_linked_deployment: false